458 new irregular verbs added
apertium/apertium-dan pull request #23
Opened 2021-11-14 09:48 UTC by mortenivar

Kevin, commits are piling up again on my branch. I thought I had it resolved with these settings in my ~/.gitconfig?
[user]  
        email = morten.bo.johansen@gmail.com
        name = Morten Bo Johansen
[credential]
        helper = cache
[pull]  
        rebase = true
[rebase]
        autoStash = true

2021-11-15 08:53 UTC, unhammer requested changes
Kan du ta en ekstra kontroll for at du med alle tegn? Det var et par manglende bokstaver der.

2021-11-15 08:53 UTC, unhammer commented on apertium-dan.dan.dix
> +<e lm="påtvinge">                      <i>påt</i><par n="tv/inge__vblex"/></e>
mangler en v her? Det skal vel være `<i>påtv</i>`

2021-11-15 08:53 UTC, unhammer commented on apertium-dan.dan.dix
> +<e lm="trælbinde">                     <i>træl</i><par n="f/inde__vblex"/></e>
dette blir «lænkeinde» uten b-en

2021-11-15 08:57 UTC, unhammer commented
> commits are piling up again on my branch

I'm not sure what's going on … Are you using github desktop? (gh desktop at least seems to not understand the gitconfig always)

If you don't have any unpushed changes (all your work is merged into github/apertium/apertium-dan), you can do a `git reset --hard origin/master` to make your local checkout be at the exact same commit as the one in this repo. But only do that if you're sure all your work is here ;)

2021-11-15 14:42 UTC, mortenivar commented
Hej Kevin

Jeg beklager. Det var en fejl i mit script, som brugte
"tegnsemantik" i stedet for "bytesemantik" i udregningen af
ordenes længde ("strlen" vs. "strbytelen") som gav problemer
med nogle enkelte ord med danske tegn. Jeg fandt også en del
andre fejl.

Meget fint at du fangede det, når jeg nu selv sover! ;)

Jeg har lavet en ændring på github, men jeg ved ikke, om jeg
har gjort det rigtigt?

Jeg håber du kan committe den. Ellers, vend tilbage og fortæl
mig. hvad jeg skal gøre.

Vh Morten

Kevin Brubeck Unhammer ***@***.***> wrote:

> @unhammer requested changes on this pull request.
> 
> Kan du ta en ekstra kontroll for at du med alle tegn? Det var et par manglende bokstaver der.
> 
> > +<e lm="skamride">                      <i>skamr</i><par n="r/ide__vblex"/></e>
> +<e lm="tilride">                       <i>tilr</i><par n="r/ide__vblex"/></e>
> +<e lm="tyndslide">                     <i>tyndsl</i><par n="r/ide__vblex"/></e>
> +<e lm="underskride">                   <i>underskr</i><par n="r/ide__vblex"/></e>
> +<e lm="afsige">                        <i>afs</i><par n="s/ige__vblex"/></e>
> +<e lm="frasige">                       <i>fras</i><par n="s/ige__vblex"/></e>
> +<e lm="fremsige">                      <i>frems</i><par n="s/ige__vblex"/></e>
> +<e lm="modsige">                       <i>mods</i><par n="s/ige__vblex"/></e>
> +<e lm="opsige">                        <i>ops</i><par n="s/ige__vblex"/></e>
> +<e lm="tilsige">                       <i>tils</i><par n="s/ige__vblex"/></e>
> +<e lm="udskrige">                      <i>udskr</i><par n="skr/ige__vblex"/></e>
> +<e lm="undsige">                       <i>unds</i><par n="s/ige__vblex"/></e>
> +<e lm="påligge">                       <i>på</i><par n="l/igge__vblex"/></e>
> +<e lm="lænkebinde">                    <i>lænke</i><par n="f/inde__vblex"/></e>
> +<e lm="trælbinde">                     <i>træl</i><par n="f/inde__vblex"/></e>
> +<e lm="påtvinge">                      <i>påt</i><par n="tv/inge__vblex"/></e>
> 
> mangler en v her? Det skal vel være `<i>påtv</i>`
> 
> > +<e lm="opvride">                       <i>opvr</i><par n="r/ide__vblex"/></e>
> +<e lm="skamride">                      <i>skamr</i><par n="r/ide__vblex"/></e>
> +<e lm="tilride">                       <i>tilr</i><par n="r/ide__vblex"/></e>
> +<e lm="tyndslide">                     <i>tyndsl</i><par n="r/ide__vblex"/></e>
> +<e lm="underskride">                   <i>underskr</i><par n="r/ide__vblex"/></e>
> +<e lm="afsige">                        <i>afs</i><par n="s/ige__vblex"/></e>
> +<e lm="frasige">                       <i>fras</i><par n="s/ige__vblex"/></e>
> +<e lm="fremsige">                      <i>frems</i><par n="s/ige__vblex"/></e>
> +<e lm="modsige">                       <i>mods</i><par n="s/ige__vblex"/></e>
> +<e lm="opsige">                        <i>ops</i><par n="s/ige__vblex"/></e>
> +<e lm="tilsige">                       <i>tils</i><par n="s/ige__vblex"/></e>
> +<e lm="udskrige">                      <i>udskr</i><par n="skr/ige__vblex"/></e>
> +<e lm="undsige">                       <i>unds</i><par n="s/ige__vblex"/></e>
> +<e lm="påligge">                       <i>på</i><par n="l/igge__vblex"/></e>
> +<e lm="lænkebinde">                    <i>lænke</i><par n="f/inde__vblex"/></e>
> +<e lm="trælbinde">                     <i>træl</i><par n="f/inde__vblex"/></e>
> 
> dette blir «lænkeinde» uten b-en
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/apertium/apertium-dan/pull/23#pullrequestreview-805778008

2021-11-15 14:48 UTC, unhammer commented
```
$ git show refs/pullreqs/23 |grep '^+.*<e.*__' | grep -v '/[^"]*_' | grep -Ev 'lm="(.*)".*<i>\1</i>'
+<e lm="foræde">                        <i>for</i><par n="æde__vblex"/></e>
+<e lm="opæde">                         <i>op</i><par n="æde__vblex"/></e>
```
det heter vel `/æde__vblex`

2021-11-15 20:50 UTC, mortenivar commented
> det heter vel /æde__vblex

Ja, det var en fejl. Der var også et par andre fejl. Filen validerer nu.

2021-11-15 20:55 UTC, mortenivar commented
> you can do a git reset --hard origin/master
Det ser ikke ud til at virke, men det er måske også ligegyldigt.

2021-11-19 14:03 UTC, closed without merging

2021-11-19 14:03 UTC, unhammer commented
merged as 45f1ff770446d2030a3f658d59fcbf9fa01a8bad

2021-11-19 14:05 UTC, unhammer commented
>> you can do a git reset --hard origin/master

> Det ser ikke ud til at virke, men det er måske også ligegyldigt.

Hvis du ikke har uinnsjekkede endringer, så bør du kunne gjøre `git fetch && git reset --hard origin/master` nå.

2021-11-20 14:01 UTC, mortenivar commented
> Hvis du ikke har uinnsjekkede endringer, så bør du kunne gjøre git fetch && git reset --hard origin/master nå.

Det virkede! Tak, Kevin.